# Generated by Django 4.1.6 on 2023-02-10 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(13)])),
                ('Month', models.CharField(max_length=50)),
                ('Ramesh', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31)])),
                ('Anju', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31)])),
                ('Manju', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31)])),
                ('Umesh', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31)])),
                ('Neha', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31)])),
            ],
        ),
    ]
